#!/bin/bash

show_help() {
    cat << EOF
Usage: ./littlesis <command>
Helpful shortcuts to the LittleSis development environment

Start/pause/stop app:
littlesis up
littlesis pause/unpause
littlesis down

Rails console: littlesis c

Mysql shell: littlesis mysql

Information:
littlesis ps
littlesis logs

Login to the containers:
littlesis login
littlesis login-root

Run all rails tests: littlesis test
This runs inside docker and will work if you don't have rvm setup

Run a single test: littlesis rspec path/to/specfile
example:
   littlesis rspec spec/models/relationship_spec.rb
This uses ruby/rvm outside of docker

Open bash console for easy test running:
littlesis spec

Reset the test database (littlesis_test)
littlesis reset-test-db

Rails logs: littlesis rails-logs

Rails test logs: littlesis rails-test-logs

Nginx logs: littlesis nginx access|error

Restart rails: littlesis restart-rails

Execute arbitrary rake command: littlesis rake [...]

For instance, to restart sphinx: littlesis rake ts:restart

Search rails app:
littlesis search <TERM>
littlesis rg <TERM>

Search test files:
littlesis spec-search <TERM>

View rails coverage:
littlesis coverage

bash shell with dev env set:
littlesis bash

redis cli: littlesis redis

download latest build log from travis:
littlesis travis-log

(store travis api token in file ./.travis_api_token)

EOF
}

web_app_exec="docker-compose exec -u app web /bin/bash -l -c"

short_help() {
    echo "Usage: ./littlesis [COMMAND]"
    echo "Helpful shortcuts to the LittleSis development environment"
    echo "More information: littlesis help"
}

nginx_logs() {
    if [[ "$1" == access || "$1" == error ]]; then
	local log_file="/var/log/nginx/${1}.log"
	docker-compose exec web /bin/bash -c "tail -f ${log_file}"
    else
	echo 'There are only two nginx logs available: access and error'
	exit 1
    fi
}

rails_search() {
    local grep_opts='-H --color -i -n'
    cd rails
    grep $grep_opts -r 'app' -e "${1}"
    grep $grep_opts -r 'lib' -e "${1}"
    grep $grep_opts -r 'config' -e "${1}"
    grep $grep_opts -r 'Gemfile' -e "${1}"
    #grep $grep_opts -r 'config' -e "${1}"
}

rails_spec_search() {
    cd rails/spec
    grep $grep_opts -r -H --color -i -n "${1}"
}

mysql_shell() {
    if [ -x "$(command -v mycli)" ];then
	local MYSQL=mycli
    else
	local MYSQL=mysql
    fi
    $MYSQL -u littlesis -pthemanbehindthemanbehindthethrone -h 127.0.0.1 littlesis
}


rails_coverage() {
    local cov_file=rails/coverage/index.html
    
    if [ -x "$(command -v chromium)" ];then
	chromium --new-window $cov_file > /dev/null 2>&1
    elif [ -x "$(command -v firefox)" ];then
	firefox --new-window $cov_file > /dev/null 2>&1
    else
	echo 'Could not find firefox or chromium'
	exit 1
    fi
}

rvm_use() {
    source ~/.rvm/scripts/rvm
    cd rails && rvm use > /dev/null
}

travis_api_token=$(cat ./.travis_api_token)
travis_repo_id=12307754

travis_curl() {
    curl -s -S -L -H "Travis-API-Version: 3" -H "Authorization: token $travis_api_token" "https://api.travis-ci.org/$1"
}

travis_build_log() {
    latest_build_id=$(travis_curl "repo/$travis_repo_id/builds?limit=1" | jq '.builds[0].id')
    latest_job_id=$(travis_curl "build/$latest_build_id" | jq '.jobs[0].id')
    travis_curl "job/$latest_job_id/log.txt" > "littlesis-travis-log-$latest_job_id.txt"
    echo "log saved to: $(readlink -f littlesis-travis-log-$latest_job_id.txt)"
}


case $1 in
    docker-compose)
	shift
	docker-compose "$@"
	;;
    up)
	docker-compose up -d
	;;
    down|ps|logs|pause|unpause)
	docker-compose "$1"
	;;
    nginx)
	shift
	nginx_logs "$@"
	;;
    mysql)
	mysql_shell
	;;
    login)
	docker-compose exec -u app web /bin/bash --login
	;;
    login-root)
	docker-compose exec web /bin/bash --login
	;;
    test)
	shift
	$web_app_exec "RAILS_ENV=test CODACY_RUN_LOCAL=true COVERAGE=true bundle exec rspec ${@}"
	;;
    rspec)
	shift
	rvm_use
	bin/rspec "$@"
	;;
    spec)
	docker-compose exec -u app web /bin/bash --login
	;;
    cmd)
	shift
	$web_app_exec "${@}"
	;;
    runner)
	shift
	$web_app_exec "RAILS_ENV=development bin/rails runner ${@}"
	;;
    console|c)
	$web_app_exec 'RAILS_ENV=development bin/rails c'
	;;
    rails-logs)
	tail -f rails/log/development.log | grep -v '/assets/'
	;;
    rails-test-logs)
	tail -f rails/log/test.log
	;;
    rake)
	shift
	$web_app_exec "RAILS_ENV=development bundle exec rake ${@}"
	;;
    restart-rails)
	docker-compose exec web /bin/bash -c 'passenger-config restart-app /home/app'
	;;
    reset-test-db)
	$web_app_exec 'RAILS_ENV=test bundle exec rake db:reset'
	;;
    search)
	shift
	rails_search "$@"
	;;
    rg)
	shift
	cd rails && rg "$@"
	;;
    spec-search)
	shift
	rails_spec_search "$@"
	;;
    cov|coverage)
	rails_coverage
	;;
    redis)
	docker-compose exec -u app web /usr/bin/redis-cli -h redis
	;;
    bash)
	export RAILS_ENV=development
	cd rails && bash --login
	;;
    travis-log)
	travis_build_log
	;;
    -h|help|--help)
	show_help
	;;
    ?*) # End of all options.
	echo 'Invalid option'
        echo 'all options: rspec, up, down, ps, logs, nginx, mysql, login, test, rspec, spec, cmd, console, rails-logs, rake, restart-rails, jasmine, reset-test-db, search, spec-search, cov, help'
        exit 1
	;;
    *)
	short_help
	;;
esac
