---
- name: Copy fail2ban configuration into place
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Ensure fail2ban is started
  service: name=fail2ban state=started

- name: OS Hardening
  include_role:
    name: dev-sec.os-hardening
 
- name: SSH Hardening
  include_role:
    name: dev-sec.ssh-hardening
  vars:
    ssh_max_auth_retries: 5

- name: Check if Ubuntu is locked
  become: yes
  command: grep -q "ubuntu:!:" /etc/shadow
  register: check_ubuntu_lock
  ignore_errors: True
  changed_when: False

- name: Unlock Ubuntu
  become: yes
  command: usermod -p "*" ubuntu
  when: check_ubuntu_lock.rc == 0
  
- name: Add additional authorized key for user ubuntu
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', item) }}"
  with_items: "{{ ubuntu_ssh_keys }}"
  when: ubuntu_ssh_keys | length > 0
  tags: keys
