#!/usr/bin/env python3

import datetime
import getpass
import os
import subprocess
import sys

if getpass.getuser() != 'root':
    sys.exit('Wordpress uploads backup script must be run as root')

wordpress_uploads_dir = '/var/www/wordpress/wordpress/wp-content/uploads'

date = datetime.date.today().strftime('%F')

archive_filename = 'wordpress-uploads-{}.tar.xz'.format(date)

archive_path = '/tmp/{}'.format(archive_filename)

tar_cmd = [ '/usr/bin/tar',
            '--create',
            '--xz',
            '--file={}'.format(archive_path),
            '--directory={}'.format(wordpress_uploads_dir),
            '.' ]

rclone_cmd = [ '/usr/bin/rclone', 'copy', archive_path ]
    
rclone_aws =  rclone_cmd + [ "aws:pai-littlesis/backups/{}".format(archive_filename) ]

rclone_digitalocean = rclone_cmd + [ "digitalocean:littlesis/backups/{}".format(archive_filename) ]
               
shred_cmd = ['/usr/bin/shred', '-u', archive_path]

subprocess.run(tar_cmd, check=True)
subprocess.run(rclone_aws)
subprocess.run(rclone_digitalocean)
subprocess.run(shred_cmd)
