#!/bin/sh

if ! test $USER = root
then
    echo "Image backup script must be run as root" >&2
    exit 1
fi

rclone sync /var/www/littlesis/public/images aws:littlesis-images-backup
rclone sync /var/www/littlesis/public/images digitalocean:littlesis/images
