default:
	@echo 'LittleSis ansible shortcuts'
# run:
# 	ansible-playbook -i ./hosts.yml littlesis.yml --extra-vars "@vars.yml"
inventory:
	@ansible-inventory -i ./inventory.yml --graph


.PHONY: inventory
