---
littlesis_packages:
  - curl
  - build-essential
  - git
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - dirmngr
  - htop
  - sysstat
  - lsof
  - tmux
  - mosh
  - libcurl4-gnutls-dev
  - imagemagick
  - libmagickwand-dev
  - automake 
  - libffi-dev
  - firefox
  - xvfb
  - python3
  - python3-pip
  - python3-dev
  - python3-mysqldb
  - fail2ban

# php
littlesis_php_packages:
  - php7.1
  - php7.1-cli
  - php7.1-common
  - php7.1-json
  - php7.1-opcache
  - php7.1-mysql
  - php7.1-readline
  - php7.1-zip
  - php7.1-xml
  - php7.1-fpm

pai_php_packages:
  - php5.6
  - php5.6-common
  - php5.6-curl
  - php5.6-fpm
  - php5.6-gd
  - php5.6-json
  - php5.6-mysql
  - php5.6-readline
  - php5.6-opcache
  - php5.6-zip
  - php5.6-xml
  - php5.6-fpm
  

# Branch/git ref of littlesis-rails to clone
littlesis_rails_version: master
  
# ssh
kex_algorithms: "diffie-hellman-group-exchange-sha256"
ciphers: "aes256-ctr,aes192-ctr,aes128-ctr"
macs: "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"

# firefox 
geckodriver_url: "https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz"

# Swap
swapfile_size: 2G
swapfile_location: /swapfile

# awscli
awscli_region: us-east-1

# nginx
nginx_ssl_ciphers: "'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'"

# nginx passenger
passenger_max_pool_size: 5
passenger_max_requests: 50000
passenger_min_instances: 1

ubuntu_ssh_keys: []

wordpress_restore_from_dump: false
wordpress_sync_uploads: false
wordpress_docker_port: 5000
wordpress_fpm_socket: /var/run/fpm-wordpress.sock

sync_pai: false
pai_restore_from_dump: false

# scripts directory
scripts_directory: /home/ubuntu/scripts
